### PR TITLE
Feature uioUHAL

### PR DESCRIPTION
**Pull request by dgastler**
This adds protocolUIO to uHAL for direct access to AXI slaves on Zynqs. 
The only requirement is that the device tree for needed slaves has a label tag with a name that matches a top level address table node id.   
This top level node will assign the IPBus address to that axi slave. 
No knowledge of the AXI memory space is needed and all code runs in userspace via UIO driver.

### CODE REVIEW

**Comment by tswilliams** [comment]
Thanks for opening this pull request. I'll post again with comment once I've taken a detailed look at the code, and discussed with the other IPbus developers. (Given how busy people are with other areas of work as well, that may take several days.)

**Comment by dgastler** [comment]
If it helps, I will be at CERN from the afternoon of Dec 4th to Dec 10th, if you want to talk in person.

**Comment by dgastler** [comment]
I did notice that Siqi had hardcoded the ARM compiler and sysroot stuff into this, so we'd have to also discuss how this would be generalized to deal with cross compiling.   I think you guys have done a little of that though.

**Comment by tswilliams** [comment]
Hi,

I've reviewed the changes, and my current understanding of the UIO client class is as follows:

 * It accesses the slaves via several different devices files - one for each top-level node in the uHAL address table.
 * The mapping between top-level uHAL nodes and devices files is determined by locating the file named `label` under `/proc/device-tree/amba_pl` that contains the correct node ID, extracting an address from the name of parent directory, and matching that address with information in `maps/map0/addr` files under `/sys/class/uio`
 * The above files (and their contents) are produced using the information contained in the device tree description file, `system-user.dtsi`

Is that summary correct? If so, this approach represents a signficant difference from the design of other file-based clients, in which a single device file (or read-write pair of device files) is used to access the FPGA's memory space.

Notably, due to a different device file being used for each top-level node, the node tree has to be instantiated in the client constructor, and the behaviour of the clients' methods depend on the contents of the associated node tree, which complicates testing. In contrast, the behaviour and implementation of the existing client classes do not depend on the node tree.

Regarding the changes related to cross compilation: Since a previous set of makefile-related changes from Tarigo and yourself were included earlier this year in pull request #144,  I think you should be acheive the same result as this branch's changes to `uhal/config/mfCommonDefs.mk` and `extern/pugixml/Makefile` simply by adding command-line arguments to the `make` command that you run - e.g. change:
```
make -j8 Set=uhal BUILD_PUGIXML=1 BUILD_UHAL_TESTS=0 BUILD_UHAL_PYCOHAL=0
```
... to:
```
COMPILETIME_ROOT=--sysroot=/mnt
make -j8 Set=uhal BUILD_PUGIXML=1 BUILD_UHAL_TESTS=0 BUILD_UHAL_PYCOHAL=0 CXX=arm-linux-gnueabihf-g++ CXXFLAGS="-g -Wall -pedantic -O3 -MMD -MP -fPIC ${COMPILETIME_ROOT}" LDFLAGS="-Wall -g -O3 -fPIC ${COMPILETIME_ROOT}"
```
But let me know if the compilation/linking commands run by that `make` command differ from those run by executing the `scripts/uioBuild/make.sh` script in this branch.

Cheers,
Tom

**Comment by alessandrothea** [comment]
On top of the technical reasons that Tom has described, there is a more substantial issue with this pull request. Uhal is conceived as the ipbus software interface library. It evolves together with its firmware counterpart and it is maintained and validated against it. 

While uhal has the flexibility to define multiple "protocols", we cannot include the client class for all possible hardware access paradigms in this repository.
This PR instead is targeted to interface uhal with AXI slaves in a manner that is distinct from the current set of slaves and clearly beyond current scope of the corresponding firmware repository. For this reason, I am afraid that this pull request cannot be accepted at this time. 

It would be nevertheless useful to understand more about this request: the context and the motivation, the structure/organization of the firmware the uio protocol interfaces with, why you think this extension should be included in uhal.

Cheers,
Alessandro

**Comment by tswilliams** [comment]
On Thursday Alessandro and I discussed the above points with Dan in person. In that discussion, I also summarised changes that I have recently made to the `ClientFactory` and `ConnectionManager` classes in order to allow client classes that are defined outside of the uHAL library to be accessible by the `ConnectionManager`. As a result, we agreed that it is more appropriate for the UIO client class from this pull request to live in another respository, and therefore this pull request will be closed without merging.

**Pull request closed without merging**
